[package]
name = "ephew_instance_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.30"
async-std = "1.12.0"
actix-web = "4.5.1"
serde = { version = "1.0.104", features = ["derive"] }
colored = "2.0.4"
toml = "0.8.12"
log = "0.4.21"
reqwest = "0.12.0"
rusqlite = { version = "0.29.0", features = ["bundled"] }
simplelog = "0.12.2"
time = "0.3.34"