[package]
name = "ephew_instance_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.30"
async-std = "1.12.0"
serde = { version = "1.0.199", features = ["derive"] }
colored = "2.0.4"
toml = "0.8.12"
log = "0.4.21"
reqwest = "0.12.3"
rusqlite = { version = "0.31.0", features = ["bundled"] }
simplelog = "0.12.2"
time = "0.3.34"
serde_json = "1.0.115"
password-hash = "0.5.0"
tokio = { version = "1.37.0", features = ["rt", "rt-multi-thread", "macros"] }
pbkdf2 = "0.12.2"
actix-session = { version = "0.9.0", features = ["cookie-session"] }

actix-identity = "0.7.1"
actix-web = "4.5.1"
home = "0.5.9"
magic-crypt = "3.1.13"
