[package]
name = "ephew_instance_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.30"
async-std = "1.12.0"
serde = { version = "1.0.104", features = ["derive"] }
colored = "2.0.4"
toml = "0.8.12"
log = "0.4.21"
reqwest = "0.12.3"
rusqlite = { version = "0.31.0", features = ["bundled"] }
simplelog = "0.12.2"
time = "0.3.36"
csv = "1.1"
serde_json = "1.0.115"
password-hash = "0.5.0"
axum = "0.7.5"
tokio = { version = "1.37.0", features = ["rt", "rt-multi-thread", "macros"] }
axum_session = { version = "0.14.0", default-features = false }
pbkdf2 = "0.12.2"
