[package]
name = "ephew_instance_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.30"
async-std = "1.12.0"
actix-web = "4.5.1"
serde = { version = "1.0.104", features = ["derive"] }
colored = "2.0.4"